### ISSUE TITLE
Client-side stuff is loading server-side

### ISSUE THREAD

**Issue by unilock** [DaFuqs/SpectralDecorations#4]
`BedrockArmorItemMixin` references `net.minecraft.client.render.RenderLayer`, which is a client-only class. It should be specified in the `client` block of the `.mixins.json`.

The following is client-only as well, but runs in the main ModInitializer:
https://github.com/DaFuqs/SpectralDecorations/blob/77645ef693f2b89efc234b7d4d3dbc06c37481a6/src/main/java/de/dafuqs/spectral_decorations/SpectralDecorations.java#L46-L59

This all causes a crash on dedicated servers :(

**Comment by DaFuqs** [comment]
Oh dang, good catch, thank you.
While the code blocks you listed are not flagged as `@Environment(EnvType.CLIENT)` they clearly reference client only classes, too.
