### ISSUE TITLE
Can't get the addon's achievement

### ISSUE THREAD

**Issue by EugeneLagonski** [DaFuqs/SpectralDecorations#6]
Minecraft 1.20.1
Modpack: All of Forge 7
Mod versions: Spectrum 1.7.1, Spectral Decorations 1.2.1

Can't get the Hue Hue Hue achievement.
Tried to investigate it and found that to get the achievement I need
to get items with the tag `spectral-decorations:effulgent_feathers`. But the mod items have the `spectral-decorations:colored_effulgent_feathers`

Could you recommend how to fix it without waiting for an update?

**Comment by DaFuqs** [comment]
You can add the items to that tag by using a data pack. [minecraft](https://minecraft.wiki/) has a great tutorial on that.

**Comment by EugeneLagonski** [comment]
Thank you! Fixed it

**Comment by DaFuqs** [comment]
Fixed in 1.3.0
