### ISSUE TITLE
[BUG] Amphoras break on any left-click

### ISSUE THREAD

**Issue by joakibj** [DaFuqs/SpectralDecorations#9]
**Describe the bug**
Wooden Amphoras and Colored Amphoras break with a single left-click. 

The Amphoras in Spectrum do not have this behavior.

**To Reproduce**
1. Create an Oak Amphora and place it down in survival
2. Left-click it with an empty hand
3. Observe that it breaks, dropping all contents

**Expected behavior**
Amphoras breaking similar to a barrel, faster with an axe.

**Minecraft version**
1.20.1

**Mod version**
1.4.1

**Comment by DaFuqs** [comment]
The same is true for the wooden beams
